modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "LGPL-2.1"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${display_name}"
authors = "${authors}"
description = '''
${description}
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "figura"
mandatory = true
versionRange = "[${figura_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="voicechat"
mandatory=true
versionRange="[${minecraft_version}-${svc_version},)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config = "${mod_id}-common.mixins.json"
[[mixins]]
config = "${mod_id}.mixins.json"